info|2019-11-12 18:12:50.395839|[INITIALIZER][initGlobalConfig],enableCompress=true,compatibilityVersion=2.1.0,versionNumber=33619968,chainId=1
error|2019-11-12 18:12:50.717202|[INITIALIZER][P2PInitializer]initConfig for P2PInitializer failed,check Port=30300,EINFO=Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >
std::exception::what: bind: Address already in use

